# Site settings
title: AANCM
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  aancm-deep-blue: '#0f387a'
  aancm-light-blue: '#a6c1d1'
  aancm-accent-blue: '#e4eaf2'
  aancm-off-white: '#f7f7f7'

# Footer settings
footer: Austrian Association for Negotiation and Conflict Management

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/negotiator.at/
  - title: facebook
    url: https://www.facebook.com/people/Austrian-Association-for-Negotiation-and-Conflict-Management/100087431952174/
  - title: linkedin
    url: https://www.linkedin.com/company/86826045/admin/feed/posts/
  - title: github
    url: https://github.com/AANCM

# Build settings
markdown: kramdown
permalink: pretty
